zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8083
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:

security:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
    username: root
    password: root