security:
  sessions: ALWAYS


logging:
  config: file:config/logback.xml

server:
  port：8099
  session:
    timeout: 1296000

spring:
  redis:
    host: 192.168.20.10
    port: 6380
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

